---
title:  "Business-oriented Typology and Characterization of Agriculture in SSA"
subtitle: "A multi-scale and cross-time framework"
author: "[Melanie Bacou](http://github.com/mbacou) for BMGF"
date:   Last updated on `r Sys.Date()`. DRAFT, DO NOT USE OR CITE.
bibliography: biblio.bib
csl: apa.csl
link-citations: yes
nocite: |
  @aasr_2016, @alvarez2014typology, @jayne2015agdev, @hazell2013urban, @douillet2014developing, @jordan2005eth, @omamo2006strategic, @bacou2015ethseg
output: 
  html_notebook:
    fig_caption: yes
    fig_height: 5
    theme: readable
    toc: yes
    toc_depth: 1
    toc_float: yes
---

# Background

This study is a prospective chapter in *AGRA Africa Agriculture Status Report (AASR) 2017*.

The overall objective of the AASR report is to [@aasr_cn_2017]:  
 
1. provide an overview of the smallholder farmers and how they have adapted to the challenges they face as economic actors; 
2. explore innovative strategies that can substantially raise the productivity and incomes of smallholder farmers; 
3. identify policies and programs that can support the movement of Africa’s farming systems from subsistence-oriented to market-oriented thriving businesses; 
4. identify the necessary conditions, appropriate technologies, and institutions that can propel and support smallholder agriculture businesses; 
5. examine the past and the present role of public and private sector investment in agriculture and the success factors that can be scaled up to accelerate transformation.  

# Method

The study should provide a context-setting chapter that attempts to characterize, scale, locate, point to prioritization of high-level smallholder commercialization strategies, opportunities and challenges. A proposed approach is to chracterize SHFs and frame business strategies within a 2-by-2 domain framework (low/high rainfed ag potential across low/high market access areas). This approach assumes that agricultural development and adaptation strategies are largely driven by pre-existing bio-physical and spatial conditions.

We propose then focusing on around half a dozen countries for which we have recent/accessible microdata (e.g. LSMS-ISA and maybe AGRA baseline surveys) to look more closely, in the same 2x2 domain framework, at specific farm household and macro characteristics to do two things:  

1. Apply some typology to distinguish between say “predominantly-subsistence” focused and “transitioning-commercial” smallholders  
2. Report on hh level variables that can provide insight into the scale of potential business development challenges and opportunities in each country. 

Key farm and household-level variables to look at may include:

* Holding size
* Income/consumption
* Access to inputs/extension
* Use of inputs
* Tenure status
* Education
* Cell-phone ownership
* Cooperative membership
* Access to credit
* Off-farm income
* ...

# Supporting Datasets

Many unpublished and mostly country-level studies have attempted to derive farmer characteristics and farm typologies across geospatial dimensions (see e.g. refs below). IFPRI in particular generated cross-country comparable household variables (derived from World Bank LSMS-ISA panels, Demographic and Health Surveys, and/or other large-scale household surveys and agricultural census).

## Cross-Country Harmonized Variables

## Other Panel Country-Level Variables



# References

